[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="TOKEN_CLASS_NAME" type="java.lang.String" --]
[#-- @ftlvariable name="LEXER_CLASS_NAME" type="java.lang.String" --]
[#-- @ftlvariable name="PARSER_CLASS_NAME" type="java.lang.String" --]
[#-- @ftlvariable name="PACKAGE_NAME" type="java.lang.String" --]
[#-- @ftlvariable name="GRAMMAR_TERMINALS" type="ru.unrealeugene.parsing.generating.Production.Symbol[]" --]